<?php
$connect=mysqli_connect("localhost","root","","garage_db");
mysqli_set_charset($connect,"utf8");
//if($connect){
    //echo"ການເຊື່ອມໂຍງສຳເລັດ";
//}else{
    //echo"ການເຊື່ອມໂຍງລົ້ມເຫຼວ";
//}
?>